# Generated by Django 5.1.2 on 2025-02-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogary',
            new_name='Category',
        ),
    ]
