# Generated by Django 5.1.2 on 2025-02-27 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_catogary_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
